name: Deploy to Heroku

on: [push]
      
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Build
        run: |
          npm ci 
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
   
    steps:
      - name: Ls
        run: ls
        
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_app_name: "zipkode"
         heroku_email: "b.boy.bip@gmail.com"
         appdir: 'dist/'
