name: Deploy to Heroku

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Build
        run: |
          npm ci 
          npm run build
        
      - name: List Files
        run: ls

      - run: git config user.email "b.boy.bip@gmail.com"
      - run: git config user.name "taktxbip"
      - run: git add -A && git commit -m "Updated code"

      - name: Push to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
         heroku_app_name: "zipkode"
         heroku_email: "b.boy.bip@gmail.com"
         dontuseforce: true
         appdir: 'dist'
