name: Deploy to Heroku

on: [push]
      
jobs:
  deploy:
    name: Build
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
      run: |
        npm i 
        run: npm run build
        run: tar czfv slug.tgz ./dist
      
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "zipkode"
          heroku_email: "b.boy.bip@gmail.com"