name: Deploy to Heroku

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Build
        run: |
          npm ci 
          npm run build
        
      - name: Ls
        run: ls
        
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 

      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a zipkode web 
      
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a zipkode web 
      
      - name: Push to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_app_name: "zipkode2"
         heroku_email: "b.boy.bip@gmail.com"
         appdir: 'dist/'
