name: Deploy to Heroku

on: [push]
      
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Clone repo
      - uses: actions/checkout@v2
      
      - name: Ls
      - run: ls
